version: '3.7'
services:
  backend:
    container_name: backend
    build: ./server
    image: soap-shop-backend
    command: bash -c "cd ./server && npm run dev"
    env_file:
      - ./server/.env
    ports:
      - 5050:5050
    volumes:
      - .:/app
      - soap-shop-tmp:/app/server/tmp

volumes:
  soap-shop-tmp:
    driver: local
